### ISSUE TITLE
RXBus appears to cause objects to be invoked more than once

### ISSUE THREAD

**Issue by MMooreGitHub** [Doublemine/RxBus#1]
Hi,

I'm running the basic commands (Subscribe, register,unregister and post)
I noticed that  method objects under:
@Subscribe(threadMode = ThreadMode.IO_THREAD)
are invoked more than once. This was never an issue when I used 
another (non-rx event bus). It's directly correlated with using yours.
Can you please research this?

Many project runs Android/Java

Thanks!

**Comment by Doublemine** [comment]
i will fix it,please wait for a moment.

**Comment by Doublemine** [comment]
@MMooreGitHub try use the version: `2.1.1`

**Comment by MMooreGitHub** [comment]
Thank you so much.   I really appreciate it!
 I will try this version and let you know.

**Comment by MMooreGitHub** [comment]
Hi @Doublemine, There are definitely improvements. However, the issue is not resolved.
Now, for  @Subscribe(threadMode = ThreadMode.IO)
objects are invoked **twice**. Before, they were invoked numerous times without bonds.

**Comment by Doublemine** [comment]
@MMooreGitHub I'm sorry about that, and could you give some code about this? I'll need a code snippet to see how you are using RxBus.

**Comment by MMooreGitHub** [comment]
Hi @Doublemine, here's a sample:
When we step through the code, all objects within [onComplete] method are called at least 2x.
In addition, the [listData] array list is doubled.

 public MyClass{
   :
   :
   
    public ArrayList<String> listData = new ArrayList<String>();
   
   @Subscribe(threadMode = ThreadMode.IO)
    private void **onComplete(**Foo f) {
    
        MyObject mo = f.myObj;
        listData.add(mo.anotherObject); 
        unObserve();
			:
    }
    
     public void unObserve(){
        RxBus.Companion.get().unRegister(this);

    }
    :
}

**Comment by Doublemine** [comment]
@MMooreGitHub First of all, the method of `@Subscribe` annotation apply must NOT be private, use `default` or `public` . And the method of `unRegister()` recommend  according to their life cycle for activity or fragment. Do Not call by inner of the method of `@Subscribe` annotation apply . just like eventBus.

**Comment by MMooreGitHub** [comment]
Hi @Doublemine 
1. I've attempted to change the accessor level (i.e private to public ). However, the issue still exists.
2. Sorry for any confusion,  public void unObserve() is not an inner method. It's outside of [*onComplete*]

Thanks

**Comment by Doublemine** [comment]
@MMooreGitHub I'm Sorry about that.  The issue only exists for the  `@Subscribe(threadMode = ThreadMode.IO)`? I guess i need more info about this.

**Comment by MMooreGitHub** [comment]
Hi,

Yes, the issue exists for @Subscribe(threadMode = "All Thread Modes")

Thank you

**Comment by Doublemine** [comment]
I have check my code and update the rxbus version to  `2.1.2-kotlin` ,Also refactor the part of Code of Subscribe Finder Check . You can try it again. If the problem still exist. Please give more code detail. Thanks.

**Comment by MMooreGitHub** [comment]
Thank you,

Do I need to change any of the dependencies below to get the 2.x.-kotlin branch?
 dependencies {

         compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
         compile 'io.reactivex.rxjava2:rxjava:2.0.5'
         compile 'com.github.Doublemine:RxBus:2.1.1'

    }

Also, I noticed [2.x.-kotlin] is just a tag rather than a branch.

**Comment by Doublemine** [comment]
Just update   compile 'com.github.Doublemine:RxBus:2.1.1' to compile 'com.github.Doublemine:RxBus:2.1.2-kotlin'

**Comment by MMooreGitHub** [comment]
Ok, I tried this. Problem still exists. see:

@Subscribe(threadMode = ThreadMode.IO)
public void **onComplete(**Foo f) {
    MyObject mo = f.myObj;
    listData.add(mo.anotherObject); 
    unObserve();
		:
}

 public void unObserve(){
    RxBus.Companion.get().unRegister(this);

}
:
}

**Comment by Doublemine** [comment]
Please give more detail about class `**Foo`.also you can clone the project and compile sample project to test it . I write little code for test  list ,and it's work fine. so maybe you should watch out the thread-safe usage about this.

**Comment by MMooreGitHub** [comment]
Ok, thank you. I'll follow-up with you if I have additional queries.

**Comment by MMooreGitHub** [comment]
Hi, this issue can be closed. It was an issue with our code not your dependency.

Thanks!
