### ISSUE TITLE
Provide ability for @Subscribe accessor methods to be protected and private

### ISSUE THREAD

**Issue by MMooreGitHub** [Doublemine/RxBus#3]
Can we provide the ability for  @Subscribe accessor methods to be protected and private?

Currently using the  [compile 'com.github.Doublemine:RxBus:2.1.2-kotlin'], the app crashes 
when using private accessor methods under the @Subscribe annotation.

This worked fine under the  [compile 'com.github.Doublemine:RxBus:2.1.1'] dependency

**Comment by Doublemine** [comment]
No ,Just same as [GreenBot/EventBus](https://github.com/greenrobot/EventBus)

**Comment by MMooreGitHub** [comment]
Ok, then I'll continue to use the  [compile 'com.github.Doublemine:RxBus:2.1.1']  version

**Comment by Doublemine** [comment]
I think it is NOT necessary  to use `private` or `protect` method to receive the rxbus-event , it may make code more confuse and other problem. Whatever, you can do what you want to do .

**Comment by MMooreGitHub** [comment]
In our case, private/ protected the methods are  a requirement of the project.
Thank you!
